baseURL = "https://leekaize.com/"
languageCode = "en-us"
title = "Lee Kai Ze"
theme = "PaperMod"

[menu]
  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 3